language: java
sudo: false
os:
- linux
branches:
  only:
  - master
jdk:
- openjdk11

cache:
  directories:
  - "$HOME/.gradle/wrapper/dists"
  - "$HOME/.gradle/caches/jars-3"
  - "$HOME/.gradle/caches/modules-2"
  - "$HOME/.gradle/caches/package-lists"
  - "$HOME/.jdk"
env:
  global:
  - _JAVA_OPTIONS=
  - GRADLE_OPTS=-Xmx1280m
before_install:
- "./gradlew --version"
install:
- true
script:
- "./gradlew --no-daemon --stacktrace -Pcoverage checkstyle test build"
before_cache:
- find $HOME/.gradle/caches -name '*.lock' -delete
after_success:
- bash <(curl -s https://codecov.io/bash)
