language: java
sudo: false
os:
- linux
branches:
  only:
  - master
jdk:
- openjdk11

cache:
  directories:
  - "$HOME/.gradle/wrapper/dists"
  - "$HOME/.gradle/caches/jars-3"
  - "$HOME/.gradle/caches/modules-2"
  - "$HOME/.gradle/caches/package-lists"
  - "$HOME/.jdk"
env:
  global:
  - _JAVA_OPTIONS=
  - GRADLE_OPTS=-Xmx1280m
before_install:
- "./gradlew --version"
install:
- true
script:
# build with OpenJDK 11
- "./gradlew --no-daemon --stacktrace -Pcoverage checkstyle test publishToMavenLocal -x javadoc"
- cd test
# test with OpenJDK 11
- "./gradlew --no-daemon --stacktrace clean build"
- "java -jar ./build/libs/auto-string-formatter-test-*.jar"
# test with Oracle JDK 8
- jdk_switcher use oraclejdk8
- "./gradlew --no-daemon --stacktrace clean build"
- "java -jar ./build/libs/auto-string-formatter-test-*.jar"
before_cache:
- find $HOME/.gradle/caches -name '*.lock' -delete
after_success:
- bash <(curl -s https://codecov.io/bash)
